apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: demo.arbelaez.org
      http:
        paths:
          - path: /api/teama
            pathType: Prefix
            backend:
              service:
                name: teama-api
                port:
                  number: 80
          - path: /api/teamb
            pathType: Prefix
            backend:
              service:
                name: teamb-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nice-ui
                port:
                  number: 80
