apiVersion: v1
kind: Service
metadata:
  labels:
    run: teama-api
  name: teama-api
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: teama-api
  type: ClusterIP
